Bitmap
SDL_Surface* Bitmap::m_pbitmapSurface
Surface for bitmap.
SDL_Texture* Bitmap::m_pbitmapTexture
Texture for bitmap (initialised to nullptr)
SDL_Renderer* Bitmap::m_pRenderer
Renderer for bitmap.
SDL_Texture* Bitmap::m_texture
Texture for bitmap.
bool Bitmap::isVisable
Boolean used for end goal (Bitmap is visable - collecting key results in false)
Referenced by draw, Pickup::Update.
bool Bitmap::isEnd
Boolean used for JSON save.
Referenced by Game::LoadObjects, Pickup::Update.
int Bitmap::m_x
Used withing bitmap.cpop to set the x, y, width and height of the bitmap.
Referenced by addoffset, Bitmap, Monster::Chase, draw, from_json, GetPositionX, GetX, SetPosition, to_json.
int Bitmap::m_y
Referenced by addoffset, Bitmap, Monster::Chase, draw, from_json, GetPositionY, GetY, SetPosition, to_json.
int Bitmap::m_w
int Bitmap::m_h
int Bitmap::spriteWidth
Width of sprite.
Referenced by draw.
float Bitmap::deltaTime
Initialise Delta Time to 0.
Referenced by draw.
float Bitmap::m_vx
Used in the draw function of Bitmap to calculate delta time.
Referenced by draw.
float Bitmap::m_vy
Referenced by draw.
float Bitmap::m_ax
Referenced by draw.
float Bitmap::m_ay
Referenced by draw.
std::string Bitmap::Name
Used in bitmap constructor for name and to return Name for GetName() function.
Referenced by Bitmap, GetName, Game::Update.
std::string Bitmap::path
Used in bitmap constructor for filepath.
Referenced by Bitmap, from_json, GetFilepath, to_json, Game::Update.
bool Bitmap::transparent
Used in bitmap constructor for usetransparency.
Referenced by Bitmap, Game::Update.
ObjectType Bitmap::type
Referenced by from_json, Hero::Hero, Monster::Monster, Pickup::Pickup, to_json.
bool Bitmap::applyGravity
std::vector<Bitmap*> Bitmap::children
Bitmap* Bitmap::m_parent
Referenced by GetParent, SetParent.
std::vector<Bitmap*> Bitmap::m_children
Referenced by AddChild, GetChildren.
bool Bitmap::IsDragged
void Bitmap::SetParent(Bitmap *parent)
References m_parent.
Bitmap * Bitmap::GetParent() const
References m_parent.
void Bitmap::AddChild(Bitmap *child)
References m_children.
std::vector< Bitmap * > & Bitmap::GetChildren()
References m_children.
Bitmap::Bitmap(SDL_Renderer *renderer, std::string filename, int xpos, int ypos, std::string name, bool useTransparency=false)
Initializes a new instance of the Bitmap class.
renderer The renderer. filename The filename. xpos The xpos. ypos The ypos. name The name. useTransparency if set to true [use transparency].
References ResourceManager::GetInstance, ResourceManager::GetSurface, m_x, m_y, Name, path, transparent.
Bitmap::~Bitmap()
Finalizes an instance of the Bitmap class.
void Bitmap::draw()
Draws this instance.
References deltaTime, isVisable, m_ax, m_ay, m_vx, m_vy, m_x, m_y, spriteWidth.
void Bitmap::addoffset(int x, int y)
Addoffsets the specified x.
x The x. y The y.
References m_x, m_y.
Referenced by Game::Update.
virtual void Bitmap::Update()
int Bitmap::GetX()
References m_x.
Referenced by Monster::Chase, Game::Update, Pickup::Update.
int Bitmap::GetY()
References m_y.
Referenced by Monster::Chase, Game::Update, Pickup::Update.
int Bitmap::GetW()
Gets the w.
Referenced by Game::Update, Pickup::Update.
int Bitmap::GetH()
Gets the h.
Referenced by Game::Update, Pickup::Update.
int Bitmap::GetPositionX()
Gets the position x.
References m_x.
int Bitmap::GetPositionY()
Gets the position y.
References m_y.
void Bitmap::SetPosition(int x, int y)
Sets the position.
x The x. y The y.
References m_x, m_y.
Referenced by Game::Update.
std::string Bitmap::GetName() const
Gets the name.
References Name.
std::string Bitmap::GetFilepath() const
References path.
SDL_Texture * Bitmap::GetTextureRef()
bool Bitmap::ContainsPoint(int x, int y) const