ProfilerSystem
__int64 ProfilerSystem::currentFrameTime
Referenced by endFrame, ProfilerSystem, startFrame, storeSample.
int ProfilerSystem::currentFrame
The current frame.
FrameMap ProfilerSystem::frameData
The frame data.
int ProfilerSystem::frameCount
float ProfilerSystem::totalFrameTime
ProfilerSystem::ProfilerSystem()
Initializes a new instance of the ProfilerSystem class.
References currentFrameTime.
ProfilerSystem::~ProfilerSystem()
Finalizes an instance of the ProfilerSystem class.
void ProfilerSystem::startFrame()
Starts the frame.
References currentFrameTime.
Referenced by Game::Update.
void ProfilerSystem::storeSample(const char *name, __int64 elapsedTime)
Stores the sample.
name The name. elapsedTime The elapsed time.
References currentFrameTime, SampleData::frameReference, SampleData::functionTime.
Referenced by Profile::~Profile.
void ProfilerSystem::endFrame()
Ends the frame.
References currentFrameTime.
Referenced by Game::Update.