Game
GameState
The game.
Uint32 Game::ResetEvent
Referenced by Monster::Chase, Game.
Uint32 Game::PickupEvent
Referenced by Pickup::Update.
std::vector<AssetData> Game::assetList
The asset list.
std::vector<Bitmap*> Game::m_Bitmaps
The m bitmaps.
Bitmap* Game::m_SelectedBitmap
The m selected bitmap.
std::vector<Bitmap*> Game::ObjectsInScene
The objects in scene.
Referenced by LoadObjects, RenderSceneHierarchy, UnLoadObjects, Update.
SDL_Point Game::mousePoint
Coordinates for mouse pointer.
Referenced by Update.
SDL_Rect Game::spriteHeroRect
SDL Rectangle for Hero.
Referenced by GetSpriteHeroRect, Update.
SDL_Rect Game::spriteMonsterRect
/// SDL Rectangle for Monster
SDL_Rect Game::spritePickupRect
/// SDL Rectangle for Pickup (Key)
Referenced by GetPickupRect.
SDL_Rect Game::spriteGoalRect
/// SDL Rectangle for Goal
SDL_Window* Game::m_Window
SDL Window for Game.
Referenced by Game, Update, ~Game.
SDL_Renderer* Game::m_Renderer
SDL Renderer for window.
Referenced by Game, LoadObjects, SetDisplayColour, Update, ~Game.
int Game::ScreenWidth
Screen Width for SDL Window.
Referenced by Game.
int Game::ScreenHeight
Screen height for SDL Window.
Referenced by Game.
std::string Game::directory
String directory for assets folder.
Input* Game::input
Input for WASD (Hero Control) and RGB fader for background colour.
Referenced by main, Update, ~Game.
int Game::themonsterXpos
Initial Starting X coordinate for Monster.
int Game::themonsterYpos
Initial Starting Y coordinate for Monster.
int Game::heroXpos
Initial Starting X coordinate for Hero.
int Game::heroYpos
Initial Starting Y coordinate for Hero.
int Game::pickupXPos
Initial starting X coordinate for Pickup (Key)
int Game::pickupYPos
Initial starting Y coordinate for Pickup (Key)
int Game::goalXPos
X Position of Goal.
int Game::goalYPos
Y Positiuon of Goal.
bool Game::showMonsterImgui
Boolean to show Monster ImGui when clicked.
bool Game::showHeroImgui
Boolean to show Hero ImGui when clicked.
bool Game::showPickupImgui
Boolean to show Pickup ImGui when clicked.
bool Game::showGoalImgui
Boolean to show Goal ImGui when clicked.
bool Game::isGoalActive
Boolean to track if the Goal is active (retrusn true when key is collected)
Bitmap* Game::AssetMousDrag
Initialised nullptr for AssetMousDrag for Drag and drop.
Referenced by Update.
bool Game::showGravityWindow
The show gravity window.
Bitmap* Game::m_SelectedObject
The m selected object.
bool Game::showSelectionGui
The show selection GUI.
GameState Game::State
The state.
bool Game::m_running
The m running.
bool Game::m_useGravity
The m use gravity.
Creature* Game::m_monster
The m monster.
Creature* Game::m_monsterTrans
The m monster trans.
Creature* Game::m_monsterTransKeyed
The m monster trans keyed.
Monster* Game::m_pTheMonster
The m p the monster.
std::vector<Monster*> Game::monsters
The monsters.
std::vector<Pickup*> Game::pickups
The pickups.
Hero* Game::m_pTheHero
A Pointer to Hero Bitmap.
Pickup* Game::m_Pickup
A Pointer to Pickup Bitmap.
Pickup* Game::m_Goal
A Pointer to Goal Bitmap.
Pickup* Game::m_Goal2
A Pointer to Goal2 Bitmap.
TTF_Font* Game::m_pSmallFont
A Pointer to allocated Small Font.
TTF_Font* Game::m_pBigFont
A pointer to allocated Big Font.
TTF_Font* Game::m_pInfoFont
A Pointer to informative text font.
std::vector<Bitmap*> Game::content
Vector of Bitmaps.
Uint8 Game::r
Red, Green, Blue and alpha levels (min = 0, max = 255)
Uint8 Game::g
Uint8 Game::b
Uint8 Game::a
int Game::xpos
X position in coordinates.
int Game::ypos
Y Position in coordinates.
ImGuiIO* Game::io
Inputs and Outputs for ImGui.
void Game::RenderSceneHierarchy()
Renders the scene hierarchy.
References ObjectsInScene.
Referenced by Update.
Game::Game()
Game Constructor.
References LoadObjects, m_Renderer, m_Window, ResetEvent, ScreenHeight, ScreenWidth.
void Game::LoadObjects()
Function for loading all game objects.
References Bitmap::isEnd, m_Renderer, ObjectsInScene.
Referenced by Game, Update.
void Game::UnLoadObjects()
Function for unloading all game objects.
References ObjectsInScene.
Referenced by Update.
Game::~Game()
Game Deconstructor.
References input, m_Renderer, m_Window.
void Game::SetDisplayColour(Uint8 r, Uint8 g, Uint8 b, Uint8 a)
Set Display Colour for SDL Window Background.
r Set Red Level (0 - 255) g Set Green Level (0 - 255) b Set Blue Level (0 - 255) a Set Alpha Level (0 - 255)
References m_Renderer.
Referenced by Update.
void Game::Update()
Update Function for Game.
References Bitmap::addoffset, AssetMousDrag, ProfilerSystem::endFrame, g_profileManager, Bitmap::GetH, Bitmap::GetW, Bitmap::GetX, Bitmap::GetY, input, KEY_A, KEY_B, KEY_D, KEY_G, KEY_Q, KEY_R, KEY_RETURN, KEY_S, KEY_W, Input::KeyIsPressed, LoadObjects, m_Renderer, m_Window, mousePoint, Bitmap::Name, ObjectsInScene, Bitmap::path, RenderSceneHierarchy, SetDisplayColour, Bitmap::SetPosition, spriteHeroRect, ProfilerSystem::startFrame, Bitmap::transparent, UnLoadObjects.
Referenced by main.
double Game::randomNumber()
Random number generator.
Returns random number Returns random number
SDL_Rect Game::GetSpriteHeroRect()
Gets SDL_Rect coordinates for Hero.
Returns Hero coordinates (which are private)
References spriteHeroRect.
SDL_Rect Game::GetPickupRect()
Gets SDL_Rect coordinates for Pickup.
Returns Hero coordinates (which are private)
References spritePickupRect.
void Game::AssetManager()
This is a summery of Asset manager.
void Game::CheckEvents()
The CheckEvents Function looks for in game events.
void Game::UpdateText(std::string msg, int x, int y, TTF_Font *font, SDL_Color colour)
Updates the text to be displayed.
msg string the message to display x X Coordinate of text y Y Coordinate of text font Font Name colour Colour of font displayed
void Game::Render()
Call to Render ImGui.
void Game::RenderObjectsWindow()
Call to Render Objects in scene and provide X and Y coordinate for each.
void Game::FindAssets()
Finds and loads contents of asset folder.
void Game::SaveWorldData()
Save Function using JSON.